### ISSUE TITLE
Issue on page /Python/06/exercises/4/spiral/instructions.html

### ISSUE THREAD

**Issue by odanielsben** [Purdue-EBEC/fall-2024#3]
"spiral_login.py" is an existing file name (from 5.2), and because the name has to be different, the autograder can't actually grade the file.

**Comment by jscarfo11** [comment]
The auto grader should still be able to grade the file as long as it is properly named. You should either have separate folders for each unit/assignment or rename your old files to something that doesn't conflict. If you need further help you should make a post on campuswire.
